site_name: MAFIA - Middleware AI Firewall Application
site_description: Middleware berbasis AI untuk mendeteksi brute force dan memblokir payload berbahaya
site_author: Tim MAFIA
repo_url: https://github.com/akarkode/mafia
repo_name: mafia

theme:
  name: material
  language: id  # Default Bahasa Indonesia
  palette:
    scheme: slate  # Dark mode
    primary: blue grey
    accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight

nav:
  - Beranda: index.md
  - English: index-en.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.betterem
  - pymdownx.tasklist:
      custom_checkbox: true
